### ISSUE TITLE
Python_Calculator App 

### ISSUE THREAD

**Issue by 12rashic** [rudranil723/hacktoberfest-begginer-repo-2022#13]
Would like to contribute to this repo by adding python calculator app .
Kindly assign the issue to me, Thank you.

**Comment by rudranil723** [comment]
do pull request

**Comment by 12rashic** [comment]
Added a PR for issue #13 Please approve for Hacktoberfest 2022

**Comment by 12rashic** [comment]
Thank you for accepting Pr , kindly apply for hacktoberfest accepted label .Thanks !
